spring:
  application:
    name: hr

  datasource:
    url: jdbc:postgresql://localhost:26257/avinty
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

  server:
    port: 8085
